# Generated by Django 5.2.8 on 2025-11-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Organização')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Nome do Proprietário')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='E-mail do Proprietário')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Telefone do Proprietário')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
