# Generated by Django 5.2.8 on 2025-11-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner_phone',
        ),
    ]
