# Generated by Django 5.2.8 on 2025-12-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Logo da Organização'),
        ),
    ]
