FROM python:3.11-slim

WORKDIR /app

ENV PYTHONBUFFERED 1

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    nginx \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "ukcrm.wsgi:application", "--bind", "0.0.0.0:8000"]