# Generated by Django 5.2.8 on 2025-11-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teams', models.ManyToManyField(blank=True, related_name='funnels', to='funnel.salesteam')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='funnel.funnel')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temperature', models.CharField(choices=[('Quente', 'Quente'), ('Morno', 'Morno'), ('Frio', 'Frio'), ('Neutro', 'Neutro')], default='Neutro', max_length=10)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='funnel.stage')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
