# Generated by Django 5.2.8 on 2025-11-30 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('funnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesteam',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='sales_teams', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='salesteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
