# Generated by Django 5.2.8 on 2025-11-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(choices=[('Summer Sale 2025', 'Summer Sale 2025'), ('Black Friday 2024', 'Black Friday 2024'), ('Product Launch', 'Product Launch'), ('Retargeting', 'Retargeting'), ('LinkedIn Ads', 'LinkedIn Ads'), ('Google Ads', 'Google Ads'), ('Organic', 'Organic'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_origin',
            field=models.CharField(choices=[('Website', 'Website'), ('Social Media', 'Social Media'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Email Campaign', 'Email Campaign'), ('Event', 'Event'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
