# Generated by Django 5.2.8 on 2025-11-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('funnel', '0002_salesteam_created_at_salesteam_members_and_more'),
        ('organization', '0002_remove_organization_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.employee', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='salesteam',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_teams', to='organization.organization'),
        ),
    ]
