# Generated by Django 5.2.8 on 2025-11-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnel', '0002_lead_campaign_lead_career_lead_contact_origin_and_more'),
        ('funnel', '0003_lead_account_salesteam_organization'),
    ]

    operations = [
    ]
