# Generated by Django 5.2.8 on 2025-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnel', '0004_merge_20251130_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
