# Generated by Django 5.2.8 on 2025-11-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnel', '0006_remove_email_unique_constraint'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE funnel_lead DROP CONSTRAINT IF EXISTS funnel_lead_email_key;',
            reverse_sql='ALTER TABLE funnel_lead ADD CONSTRAINT funnel_lead_email_key UNIQUE (email);',
        ),
    ]
