# Generated by Django 5.2.8 on 2025-12-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnel', '0007_drop_email_unique_constraint_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gain_loss_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='gain_loss_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Gained', 'Gained'), ('Lost', 'Lost')], default='Active', max_length=10),
        ),
    ]
