# Generated by Django 5.2.8 on 2025-12-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnel', '0008_lead_gain_loss_reason_lead_gain_loss_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='visible_to_closer',
            field=models.BooleanField(default=True, verbose_name='Visível para Closer'),
        ),
        migrations.AddField(
            model_name='stage',
            name='visible_to_sdr',
            field=models.BooleanField(default=True, verbose_name='Visível para SDR'),
        ),
    ]
