import type { Column } from "@/components/BoardColumn";
import type { Task } from "@/components/TaskCard";

export const defaultCols = [
  {
    id: "todo" as const,
    title: "Todo",
    subtitle_left: "3 negócios",
    subtitle_right: "R$ 21.000,00",
  },
  {
    id: "in-progress" as const,
    title: "In progress",
    subtitle_left: "3 negócios",
    subtitle_right: "R$ 21.000,00",
  },
  {
    id: "done" as const,
    title: "Done",
    subtitle_left: "3 negócios",
    subtitle_right: "R$ 21.000,00",
  },
] satisfies Column[];

export const initialTasks: Task[] = [
  {
    id: "task1",
    columnId: "done",
    title: "Nome do Lead",
    content: "Project initiation and planning",
    earning: 7000.00,
    temperature: "Neutro",
  },
  {
    id: "task2",
    columnId: "done",
    title: "Nome do Lead",
    content: "Gather requirements from stakeholders",
    earning: 7000.00,
    temperature: "Quente",
  },
  {
    id: "task3",
    columnId: "done",
    title: "Nome do Lead",
    content: "Create wireframes and mockups",
    earning: 7000.00,
    temperature: "Frio",
  },
  {
    id: "task4",
    columnId: "in-progress",
    title: "Nome do Lead",
    content: "Develop homepage layout",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task5",
    columnId: "in-progress",
    title: "Nome do Lead",
    content: "Design color scheme and typography",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task6",
    columnId: "todo",
    title: "Nome do Lead",
    content: "Implement user authentication",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task7",
    columnId: "todo",
    title: "Nome do Lead",
    content: "Build contact us page",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task8",
    columnId: "todo",
    title: "Nome do Lead",
    content: "Create product catalog",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task9",
    columnId: "todo",
    title: "Nome do Lead",
    content: "Develop about us page",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task10",
    columnId: "todo",
    title: "Nome do Lead",
    content: "Optimize website for mobile devices",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task11",
    columnId: "todo",
    content: "Integrate payment gateway",
    title: "Nome do Lead",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task12",
    columnId: "todo",
    title: "Nome do Lead",
    content: "Perform testing and bug fixing",
    earning: 7000.00,
    temperature: "Morno",
  },
  {
    id: "task13",
    columnId: "todo",
    title: "Nome do Lead",
    content: "Launch website and deploy to server",
    earning: 7000.00,
    temperature: "Morno",
  },
];
